import type { QSO, Activation } from '../types/qso';

/**
 * Format a single ADIF field: <NAME:length>value
 * Length is the byte count (UTF-8) of the value.
 */
export function formatAdifField(name: string, value: string): string {
  const bytes = new TextEncoder().encode(value).length;
  return `<${name}:${bytes}>${value}`;
}

/**
 * Band plan: convert frequency in kHz to band name.
 * Covers all standard HF/VHF/UHF amateur bands.
 */
export function frequencyToBand(freqKHz: number): string {
  const bands: Array<{ min: number; max: number; name: string }> = [
    { min: 135.7, max: 137.8, name: '2190m' },
    { min: 472, max: 479, name: '630m' },
    { min: 1800, max: 2000, name: '160m' },
    { min: 3500, max: 4000, name: '80m' },
    { min: 5330, max: 5406, name: '60m' },
    { min: 7000, max: 7300, name: '40m' },
    { min: 10100, max: 10150, name: '30m' },
    { min: 14000, max: 14350, name: '20m' },
    { min: 18068, max: 18168, name: '17m' },
    { min: 21000, max: 21450, name: '15m' },
    { min: 24890, max: 24990, name: '12m' },
    { min: 28000, max: 29700, name: '10m' },
    { min: 50000, max: 54000, name: '6m' },
    { min: 70000, max: 71000, name: '4m' },
    { min: 144000, max: 148000, name: '2m' },
    { min: 222000, max: 225000, name: '1.25m' },
    { min: 420000, max: 450000, name: '70cm' },
    { min: 902000, max: 928000, name: '33cm' },
    { min: 1240000, max: 1300000, name: '23cm' },
    { min: 2300000, max: 2450000, name: '13cm' },
  ];

  for (const band of bands) {
    if (freqKHz >= band.min && freqKHz <= band.max) {
      return band.name;
    }
  }
  return '';
}

/**
 * Format latitude for ADIF MY_LAT field (e.g. "N047 16.200")
 */
function formatAdifLat(lat: number): string {
  const dir = lat >= 0 ? 'N' : 'S';
  const absLat = Math.abs(lat);
  const deg = Math.floor(absLat);
  const min = (absLat - deg) * 60;
  return `${dir}${String(deg).padStart(3, '0')} ${min.toFixed(3)}`;
}

/**
 * Format longitude for ADIF MY_LON field (e.g. "E013 45.600")
 */
function formatAdifLon(lon: number): string {
  const dir = lon >= 0 ? 'E' : 'W';
  const absLon = Math.abs(lon);
  const deg = Math.floor(absLon);
  const min = (absLon - deg) * 60;
  return `${dir}${String(deg).padStart(3, '0')} ${min.toFixed(3)}`;
}

/**
 * Try to extract a program name from a reference string.
 * E.g. "OE/TI-001" -> "SOTA", "OE-0012" -> "POTA", "OEFF-0123" -> "WWFF"
 * Returns empty string if unknown.
 */
function guessProgram(ref: string): string {
  if (/^[A-Z]{1,2}\/[A-Z]{2}-\d{3}$/i.test(ref)) return 'SOTA';
  if (/^[A-Z]{1,2}-\d{4,}$/i.test(ref)) return 'POTA';
  if (/^[A-Z]{2,4}FF-\d{4}$/i.test(ref)) return 'WWFF';
  if (/^GMA/i.test(ref)) return 'GMA';
  return '';
}

/**
 * Generate a complete ADIF 3.1.4 string from QSOs and optional activation context.
 */
export function generateAdif(qsos: QSO[], activation?: Activation): string {
  const lines: string[] = [];

  // Header
  lines.push('Generated by xOTA Map - https://xotamap.oeradio.at');
  lines.push(formatAdifField('ADIF_VER', '3.1.4'));
  lines.push(formatAdifField('PROGRAMID', 'xOTAMap'));
  lines.push(formatAdifField('PROGRAMVERSION', '0.1.0'));
  lines.push('<EOH>');
  lines.push('');

  // Determine primary reference from activation
  const primaryRefStr = activation?.references?.[0];

  for (const qso of qsos) {
    const fields: string[] = [];

    // Required fields
    fields.push(formatAdifField('CALL', qso.callsign));

    // Parse ISO timestamp
    const dt = new Date(qso.timestamp);
    const dateStr = [
      dt.getUTCFullYear(),
      String(dt.getUTCMonth() + 1).padStart(2, '0'),
      String(dt.getUTCDate()).padStart(2, '0'),
    ].join('');
    fields.push(formatAdifField('QSO_DATE', dateStr));

    const timeStr = [
      String(dt.getUTCHours()).padStart(2, '0'),
      String(dt.getUTCMinutes()).padStart(2, '0'),
      String(dt.getUTCSeconds()).padStart(2, '0'),
    ].join('');
    fields.push(formatAdifField('TIME_ON', timeStr));

    // Frequency: stored as kHz, ADIF wants MHz
    const freqMHz = (qso.frequency / 1000).toFixed(6).replace(/0+$/, '').replace(/\.$/, '');
    fields.push(formatAdifField('FREQ', freqMHz));

    // Band
    const band = frequencyToBand(qso.frequency);
    if (band) {
      fields.push(formatAdifField('BAND', band));
    }

    // Mode
    fields.push(formatAdifField('MODE', qso.mode));

    // RST
    fields.push(formatAdifField('RST_SENT', qso.rstSent));
    fields.push(formatAdifField('RST_RCVD', qso.rstReceived));

    // Grid locator from QSO
    if (qso.myGrid) {
      fields.push(formatAdifField('MY_GRIDSQUARE', qso.myGrid));
    }

    // Lat/lon from QSO
    if (qso.myLat != null && qso.myLon != null) {
      fields.push(formatAdifField('MY_LAT', formatAdifLat(qso.myLat)));
      fields.push(formatAdifField('MY_LON', formatAdifLon(qso.myLon)));
    }

    // Program reference (SIG / SIG_INFO)
    // Use per-QSO references first, then fall back to activation references
    const refStr = qso.references?.[0] ?? primaryRefStr;
    if (refStr) {
      const prog = guessProgram(refStr);
      if (prog) {
        fields.push(formatAdifField('SIG', prog));
        fields.push(formatAdifField('SIG_INFO', refStr));
        fields.push(formatAdifField('MY_SIG', prog));
        fields.push(formatAdifField('MY_SIG_INFO', refStr));
      } else {
        // Unknown program — still export the reference as comment context
        fields.push(formatAdifField('SIG_INFO', refStr));
        fields.push(formatAdifField('MY_SIG_INFO', refStr));
      }
    }

    // Notes as COMMENT
    if (qso.notes) {
      fields.push(formatAdifField('COMMENT', qso.notes));
    }

    lines.push(fields.join(' ') + ' <EOR>');
    lines.push('');
  }

  return lines.join('\n');
}

/**
 * Generate ADIF and trigger a browser file download.
 *
 * @param qsos - QSOs to export
 * @param activation - Optional activation context
 * @param program - If given, filters to this program reference only
 */
export function exportAdifFile(qsos: QSO[], activation?: Activation, program?: string): void {
  // Filter QSOs to those matching the requested program reference, if specified
  let filteredQsos = qsos;
  if (program) {
    filteredQsos = qsos.filter(
      (q) => q.references?.includes(program) || activation?.references?.includes(program),
    );
    // If filtering left nothing, export all (better than empty file)
    if (filteredQsos.length === 0) filteredQsos = qsos;
  }

  const adifContent = generateAdif(filteredQsos, activation);

  // Build filename: {YYYY-MM-DD}_{reference}_{n}qsos.adi
  const now = new Date();
  const dateStr = [
    now.getUTCFullYear(),
    String(now.getUTCMonth() + 1).padStart(2, '0'),
    String(now.getUTCDate()).padStart(2, '0'),
  ].join('-');

  const refForFilename = program ?? activation?.references?.[0];
  const refPart = refForFilename
    ? '_' + refForFilename.replace(/[/\\:*?"<>|]/g, '-')
    : '';
  const filename = `${dateStr}${refPart}_${filteredQsos.length}qsos.adi`;

  // Trigger browser download
  const blob = new Blob([adifContent], { type: 'text/plain;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
